### ISSUE TITLE
Library v3.0.0 Can't download

### ISSUE THREAD

**Issue by rivaisali** [arsvechkarev/TimerX#8]
please resolve

**Comment by raheemadamboev** [comment]
cant download too

**Comment by zhombie** [comment]
Library is available at Jitpack: https://jitpack.io/#arsvechkarev/timerx/3.0.0

> README.md has incorrect link to dependency. @arsvechkarev could you replace the incorrect dependency link with relevant one?

Actually, @rivaisali @raheemadamboev the link to dependency should be `implementation 'com.github.arsvechkarev:timerx:3.0.0'`

**Comment by zhombie** [comment]
However, `implementation 'com.github.arsvechkarev:timerx:3.0.0'` is not able to find `timerx-formatting` module on its own somehow

**Comment by ghost** [comment]
@zhombie @arsvechkarev I'm having issues while adding the 3.0.0 version for this library. I want to use the 3.0.0 version due to the added feature of startFrom in Stopwatch but not able to run my project due to the below error, could you help me resolve this issue? 

![image](https://user-images.githubusercontent.com/97949976/170974071-3591a6f0-c028-4257-b352-d4b254829822.png)

**Comment by arsvechkarev** [comment]
Hi everybody! I am obviously commenting too late, very sorry for not addressing your issues earlier. I've just released version 3.1.0, in which I fixed the issue with jitpack alongside with some minor updates, so version 3.0.0 is obsolete from now on. I'm going to close this issue, if anyone experiences problems with the new version, feel free to open a new issue.

**Comment by Pezcraft** [comment]
not available again
